### ISSUE TITLE
Missing type declarations in dist folder

### ISSUE THREAD

**Issue by saramorillon** [icebob/fakerator#174]
Hello,

I can see that a fakerator.d.ts file exists at the root of the project, but it is not bundled in dist folder and not referenced in package.json.
As a result, it is not usable in a typescript project.
Could you add it please?

Thank you.

**Comment by riderx** [comment]
@saramorillon i did PR for that ! i tested it locally it works :)
https://github.com/icebob/fakerator/pull/176
